### ISSUE TITLE
Game Feedback

### ISSUE THREAD

**Issue by JosieAilsa** [LorenzoTurco/snake#1]
## Version Control

- Not nearly enough commits here Lorenzo - I appreciate you did this last minute but you should still be adding and committing with every bit of functionality you add.

## Site Output

- The game works well and you did an amazing job of churning this out very quickly.
- I would suggest changing the colour of the board or the colour of the food - you have really poor contrast ratio with that orange/red.

## Readability

- You’ve broken down your logic into lots of small modular functions.
- Your functions and variables all have really descriptive names.
- You’ve got global variables/functions/event listeners clearly separated.

To improve: 

- Starting thinking about pulling helper functions/variables into separate files

## Responsiveness

- You need arrow keys to control the direction of the snake so it doesn’t work on mobile. Add some buttons to resolve this.

## Code Knowledge and Use

- You are starting to use parameters and returning from functions which is great 🤩
- **You only need to use let if you are going to reassign a variable ie say.** Most of the time you are using let, you should be using const. Your DOM references should be constants.

**Comment by LorenzoTurco** [comment]
Thank you for your feedback.

> I would suggest changing the colour of the board or the colour of the food

- [x] Food now glows on screen.

> You need arrow keys to control the direction of the snake so it doesn’t work on mobile.

- [x] Canvas size and it's components are now responsive and mobile users are able to use touchscreen commands (e.g. swipe up) to move the snake.

> Most of the time you are using let, you should be using const. Your DOM references should be constants.

- [x]  Fixed
